name: Process JSON File

on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours
  workflow_dispatch: # Allows manual triggering from the Actions tab

permissions: # Add this section to request write permissions
  contents: write

jobs:
  json_replace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11' # Specify your desired Julia version

      - name: Install Julia packages
        run: julia -e 'using Pkg; Pkg.add(["HTTP", "JSON3"])'

      - name: Debug - List files and directories
        run: |
          pwd
          ls -al

      - name: Run Julia script to replace IPv4 with IPv6
        run: julia ${{ github.workspace }}/WoW.jl

      - name: Commit and push changes
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Attempt 8: Fetch tree_id from API');
            const outputFilePath = process.env.GITHUB_WORKSPACE + '/modified_file.json'; // Explicit path construction
            const fs = require('fs');

            // Fetch the commit SHA of the main branch
            const commitData = await github.rest.git.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.payload.after || context.sha // Use 'after' from push event or current SHA for others
            });
            const treeSha = commitData.data.tree.sha;
            console.log(`Tree SHA: ${treeSha}`);


            if (fs.existsSync(outputFilePath)) {
              console.log('Modified JSON file exists. Committing changes.');
              await github.rest.repos.createOrUpdateFileContents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: 'modified_file.json',
                message: 'Automated update: Replace ipv4 with ipv6 in JSON',
                content: fs.readFileSync(outputFilePath, 'base64'),
                sha: treeSha // Use fetched treeSha
              });
            } else {
              console.log('Modified JSON file was not created, skipping commit.');
            }