name: Process JSON File

on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  json_replace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11' # Specify your desired Julia version

      - name: Install Julia packages
        run: julia -e 'using Pkg; Pkg.add(["HTTP", "JSON3"])'

      - name: Debug - List files and directories
        run: |
          pwd
          ls -al

      - name: Run Julia script to replace IPv4 with IPv6
        run: julia ${{ github.workspace }}/WoW.jl

      - name: Commit and push changes
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Hello from GitHub Script!');
            console.log(process.env.GITHUB_WORKSPACE);